language: csharp
solution: ./src/DesignPattern.sln
install: 
  - nuget restore ./src/DesignPattern.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script: 
  - xbuild /p:Configuration=Release ./src/DesignPattern.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./src/DesignPattern.Test/bin/Release/DesignPattern.Test.dll
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./src/Function.Test/bin/Release/Function.Test.dll